name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - name: Compile SVG
        run: typst compile main.typ resume.svg
      - name: Upload SVG artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-svg
          path: resume.svg
